config/routes.rb
MyApp::Application.routes.draw do

  resources :profils
  resources :offres
  get "profils/search"
  post "profils/search"

  

  get "welcome/index"
  get "welcome/help"

  root 'welcome#index'

  

end

app/models/offre.rb
class Offre < ActiveRecord::Base
end

app/models/profil.rb
class Profil < ActiveRecord::Base

def rouge


 "couleur verte"


end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offres_controller.rb
class OffresController < ApplicationController
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController


def index

#@profils=Profil.all

#@profil=Profil.find(2)

#var=Profil.find(:all, :conditions => "nom = 'louis' ")

#@li=var[0]


@profils=Profil.new

#@profils2=Profil.all


#@profils2=Profil.find(:all,
                     # :conditions => "nom= '3'",
                      #:order      =>  "id DESC")

a=4


@profils2=Profil.find(:all,
                     :conditions => "",
                      :order      =>  "id DESC",
                      :limit      =>  10,
                       :offset      =>  a*10)     # numero de page qu on souhaite afficher
 





end


def show

	@profils4=params[:id]
	
	@profils6=Profil.find(:all,
                     :conditions => "",
                      :order      =>  "id DESC",
                      :limit      =>  10,
                       :offset      =>  @profils4.to_i*10)     # numero de page qu on souhaite afficher
 


	@profils=Profil.new

	







end













def search

@profils=Profil.new

#@profils3=Profil.find(6)


#@profils3=Profil.find(:all,:conditions => "nom= 'louis'")

#farming="loui"

#@farming2=params[:profil]
@farming2=params[:profil][:nom]


#farming3=params[:profil]




#@profils3=Profil.find(:all,:conditions => ["nom=:nom",params[:profil]])

#@profils3=Profil.where("nom = ?", params[:profil])

#@profils3=Profil.find(:all,:conditions => ["nom like ?","loui"])

#@profils3=Profil.where("nom LIKE ?" , "%#{farming}%")   #  requette pour lister bdd en demandant les premieres lettres du nom

@profils3=Profil.where("nom LIKE ?" , "%#{@farming2}%")   #  requette pour lister bdd en demandant les premieres lettres du nom



end





end

app/controllers/profils_controller2.rb
class ProfilsController < ApplicationController


def index

#@profils=Profil.all

#@profil=Profil.find(2)

#var=Profil.find(:all, :conditions => "nom = 'louis' ")

#@li=var[0]


@profils=Profil.new

#@profils2=Profil.all


#@profils2=Profil.find(:all,
                     # :conditions => "nom= '3'",
                      #:order      =>  "id DESC")

a=4


@profils2=Profil.find(:all,
                     :conditions => "",
                      :order      =>  "id DESC",
                      :limit      =>  10,
                       :offset      =>  a*10)     # numero de page qu on souhaite afficher
 





end


def show

end


def change

end


def search

@profils=Profil.new

#@profils3=Profil.find(6)


#@profils3=Profil.find(:all,:conditions => "nom= 'louis'")

#farming="loui"

#@farming2=params[:profil]
@farming2=params[:profil][:nom]

#farming3=params[:profil]




#@profils3=Profil.find(:all,:conditions => ["nom=:nom",params[:profil]])

#@profils3=Profil.where("nom = ?", params[:profil])

#@profils3=Profil.find(:all,:conditions => ["nom like ?","loui"])

#@profils3=Profil.where("nom LIKE ?" , "%#{farming}%")   #  requette pour lister bdd en demandant les premieres lettres du nom

@profils3=Profil.where("nom LIKE ?" , "%#{@farming2}%")   #  requette pour lister bdd en demandant les premieres lettres du nom



end


end

app/controllers/reserve profil controler/profils_controller.rb
class ProfilsController < ApplicationController


def index

#@profils=Profil.all

#@profil=Profil.find(2)

#var=Profil.find(:all, :conditions => "nom = 'louis' ")

#@li=var[0]


@profils=Profil.new

@profils2=Profil.all


end


def show

end


def search

@profils=Profil.new

#@profils3=Profil.find(6)


#@profils3=Profil.find(:all,:conditions => "nom= 'louis'")

#farming="loui"

#@farming2=params[:profil]
@farming2=params[:profil][:nom]

#farming3=params[:profil]




#@profils3=Profil.find(:all,:conditions => ["nom=:nom",params[:profil]])

#@profils3=Profil.where("nom = ?", params[:profil])

#@profils3=Profil.find(:all,:conditions => ["nom like ?","loui"])

#@profils3=Profil.where("nom LIKE ?" , "%#{farming}%")   #  requette pour lister bdd en demandant les premieres lettres du nom

@profils3=Profil.where("nom LIKE ?" , "%#{@farming2}%")   #  requette pour lister bdd en demandant les premieres lettres du nom



end


end

app/controllers/reserve profil controler/profils_controller2.rb
class ProfilsController < ApplicationController


def index

#@profils=Profil.all

#@profil=Profil.find(2)

#var=Profil.find(:all, :conditions => "nom = 'louis' ")

#@li=var[0]


@profils=Profil.new

#@profils2=Profil.all


#@profils2=Profil.find(:all,
                     # :conditions => "nom= '3'",
                      #:order      =>  "id DESC")

a=4


@profils2=Profil.find(:all,
                     :conditions => "",
                      :order      =>  "id DESC",
                      :limit      =>  10,
                       :offset      =>  a*10)     # numero de page qu on souhaite afficher
 





end


def show

end


def search

@profils=Profil.new

#@profils3=Profil.find(6)


#@profils3=Profil.find(:all,:conditions => "nom= 'louis'")

#farming="loui"

#@farming2=params[:profil]
@farming2=params[:profil][:nom]

#farming3=params[:profil]




#@profils3=Profil.find(:all,:conditions => ["nom=:nom",params[:profil]])

#@profils3=Profil.where("nom = ?", params[:profil])

#@profils3=Profil.find(:all,:conditions => ["nom like ?","loui"])

#@profils3=Profil.where("nom LIKE ?" , "%#{farming}%")   #  requette pour lister bdd en demandant les premieres lettres du nom

@profils3=Profil.where("nom LIKE ?" , "%#{@farming2}%")   #  requette pour lister bdd en demandant les premieres lettres du nom



end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offres/index.html.erb
<h1> Les offres </h1>

app/views/profils/blabla.erb
all profils <br>


<% form_for :@profils, :url => {:action => :search } do |t|  %>

 votre nom <%= t.text_field :nom, :size => 30 %> 


 <%= submit_tag %>


<% end  %>

app/views/profils/page.html.erb
<h3>Page</h3>

app/views/profils/reserve/index.html.erb
<h1>all profils</h1>

	<ul id ="articles">
<% @profils.each do | profil|  %>


<li> <%= profil.nom   %>  </li>

<% end  %>

app/views/profils/search.erb
<h3>Post a Comment</h3>

<%= form_for @profils, :url => { :action => "search" } do |t| %>

 <p>votre nom <%= t.text_field :nom, :size => 30 %> </p>


 <%= submit_tag %>


<% end  %>

<h3>  Ma recherche: </h3>



<% @profils3.each do |t| %>

<p><%= t.nom  %></p>

<p><%= t.id  %></p>


<% end %>


<p><%= @farming2  %></p>

app/views/profils/show.html.erb
<h3>Show</h3>


<%= @profils4 %>


<h3>Post a Comment</h3>





<%= form_for @profils, :url => { :action => "search" } do |t| %>

 <p>votre nom <%= t.text_field :nom, :size => 30 %> </p>


 <%= submit_tag %>


<% end  %>


<h3> listes rouge </h3>


 <% @profils6.each do |t|  %>

<p>
<%=  t.nom  %>

<%=  t.id  %>

<%=  t.rouge  %>


</p>
<% end %>



<p>

	

	<% page=1  %>

	<% while page<11 %>



 
 <a href="/profils/<%= page %>">  <%= page %> </a> 

 <% page+=1 %>
 <% end %>
 

	</p>

app/views/welcome/help.html.erb
<h1>Welcome#help</h1>
<p>Find me in app/views/welcome/help.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Voir le profils:<%= link_to "profil", profils_path %></p>